#!/bin/bash -e

# This build script is meant to be used in conjunction with tcprelay.py,
# and with the assumption that you have your public key stored in your 
# iDevice (otherwise it would ask for your password every time and that would
# be a pain in the ass.

# Can supply 1 argument for port number; default is 2222.

if [ -n "$1" ]
then
    LGRPORTNO="$1"
else
    LGRPORTNO="2222"
fi

make
scp -P $LGRPORTNO obj/lfetcher.dylib root@localhost:/Library/MobileSubstrate/DynamicLibraries/
scp -P $LGRPORTNO lfetcher.plist root@localhost:/Library/MobileSubstrate/DynamicLibraries/
scp -P $LGRPORTNO Preferences/lfetcher.plist root@localhost:/Library/PreferencesLoader/Preferences/
echo "Respringing..."
ssh -p $LGRPORTNO -l root localhost killall SpringBoard
