#!/bin/bash -e

# This build script is meant to be used in conjunction with tcprelay.py,
# and with the assumption that you have your public key stored in your 
# iDevice (otherwise it would ask for your password every time and that would
# be a pain in the ass.
make
scp -P 2222 obj/LyricsGrabber.dylib root@localhost:/Library/MobileSubstrate/DynamicLibraries
echo "Respringing..."
ssh -p 2222 -l root localhost killall SpringBoard
